<?php

namespace ContainerHWdYb9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_InfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_mongodb.odm.command.info' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/src/Command/DoctrineODMCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/src/Command/InfoDoctrineODMCommand.php';

        $container->privates['doctrine_mongodb.odm.command.info'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand(($container->services['doctrine_mongodb'] ?? self::getDoctrineMongodbService($container)));

        $instance->setName('doctrine:mongodb:mapping:info');

        return $instance;
    }
}
