<?php

namespace Container2WNLvhg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CountryType' shared autowired service.
     *
     * @return \App\Form\CountryType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CountryType.php';

        return $container->privates['App\\Form\\CountryType'] = new \App\Form\CountryType();
    }
}
